name: Assert version is incremented

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    permissions:
      packages: read

    uses: UMRoboticsTeam/umrt-ci-cd/.github/workflows/standard-semver.yaml@main
